export const CHANGE_NEW_CONTACT_EMAIL = 'CHANGE_NEW_CONTACT_EMAIL'
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT'
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR'
export const ADD_CONTACT_IS_SUCCESS = 'ADD_CONTACT_IS_SUCCESS'